services:
  cleancode-js-devoir:
    image: node:20
    container_name: cleancode-js-devoir
    volumes:
      - ./:/home/cleancode-js-devoir
    working_dir: /home/cleancode-js-devoir
    ports:
      - 5273:5173
      - 4273:4173
      - 3210:3000
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Paris
      - HOST=0.0.0.0
    restart: unless-stopped
    tty: true
